title: Cycle263 Blog
description: Stay hungry, stay foolish. 
keyword: "前端, 前端大世界, javascript, es6, css, html, react, webpack, jquery, 前端开发, http, 个人博客, web"
theme: jekyll-theme-slate
baseurl: "/blogs"    
suffix: ".md"    